version: "3.8"

services:
    ts-application-template:
        build:
            context: .
            dockerfile: Dockerfile

        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "10m"

        restart: unless-stopped
